const express = require('express')
const router = express.Router()
const bodyParser = require('body-parser')
const urlencodedParser = bodyParser.json()
const api_controllers = require('../controllers/controllers.api')
router.post('/chuandoan',urlencodedParser,api_controllers.chuandoan)
router.get('/benh',urlencodedParser,api_controllers.benh)
router.post('/ketqua',urlencodedParser,api_controllers.thongke)
router.post('/tracuu',urlencodedParser,api_controllers.tracuu)
router.get('/timkiem',api_controllers.timkiem)
router.get('/thongketheoloaibenh',api_controllers.thongketheoloaibenh)
router.get('/thongketheokhuvuc',api_controllers.thongketheokhuvuc)
router.get('/dscacbenh',api_controllers.dscacbenh)
router.get('/dscacbenhNoType',api_controllers.dsbenhNoType)
router.get('/gettrieuchung',api_controllers.getTrieuChung)
router.get('/getgionglua',api_controllers.getGiongLua)
module.exports = router;